## Notebook Is Awesome

## NumPy is FAST

In [2]:
import numpy as np

In [3]:
a = np.array([2,3,4])

In [4]:
a

array([2, 3, 4])

In [5]:
a.dtype

dtype('int32')

In [6]:
a * 6

array([12, 18, 24])

In [11]:
np.linspace(0, 1, 9)  

array([ 0.   ,  0.125,  0.25 ,  0.375,  0.5  ,  0.625,  0.75 ,  0.875,  1.   ])

In [21]:
a = np.arange(0, 2 ** 20)  

In [24]:
l = range(0, 2 ** 20)

In [26]:
len(a), len(l)

(1048576, 1048576)

In [27]:
%%timeit
[i*i for i in l]

10 loops, best of 3: 177 ms per loop


In [28]:
%%timeit
a * a

1000 loops, best of 3: 1.56 ms per loop


## Pandas is Crazy

In [ ]:
# Find docker + ipython notebook. Container per group / server with folders.

In [31]:
import pandas as pd

In [32]:
%%time
cast = pd.DataFrame.from_csv('./intro_data/cast.csv', index_col=None)

Wall time: 4.28 s


In [33]:
cast.head()

title  year     name   type                character     n
0         Suuri illusioni  1985   Homo $  actor                   Guests  22.0
1     Battle of the Sexes  2017  $hutter  actor          Bobby Riggs Fan  10.0
2    Secret in Their Eyes  2015  $hutter  actor          2002 Dodger Fan   NaN
3              Steve Jobs  2015  $hutter  actor  1988 Opera House Patron   NaN
4  Straight Outta Compton  2015  $hutter  actor              Club Patron   NaN

In [34]:
%%time
release_dates = pd.read_csv('./intro_data/release_dates.csv', index_col=None,
                            parse_dates=['date'], infer_datetime_format=True)

Wall time: 585 ms


In [36]:
release_dates.head()

title  year      country       date
0   #73, Shaanthi Nivaasa  2007        India 2007-06-15
1                 #Beings  2015      Romania 2015-01-29
2  #Ewankosau saranghaeyo  2015  Philippines 2015-01-21
3                 #Horror  2015          USA 2015-11-20
4                 #Horror  2015           UK 2016-05-16

In [37]:
titles = cast[['title', 'year']].drop_duplicates().reset_index(drop=True)
titles.head()

title  year
0         Suuri illusioni  1985
1     Battle of the Sexes  2017
2    Secret in Their Eyes  2015
3              Steve Jobs  2015
4  Straight Outta Compton  2015

In [39]:
# 1. What is the name and year of the very first movie ever made?

titles.sort_values('year').head(1)

title  year
130478  Miss Jerry  1894

In [43]:

# 1. How many years into the future does the IMDB database list movie titles?

titles.sort_values('year').tail(3)

title  year
66884   Clutch Control  2022
165691        Avatar 4  2022
34974    New Rebellion  2023

In [44]:
# 1. How many movies listed in `titles` came out in 1950?

len(titles[titles.year == 1950])

# or: (titles.year == 1950).sum()

901

In [ ]:

# 2. What are the 15 most common movie titles in film history?

titles.title.value_counts().head(15)

In [ ]:
# 5. What are the 5 longest movie titles ever?

pd.set_option('max_colwidth', 300)

t = titles.copy()
t['len'] = t.title.str.len()
t = t.sort('len', ascending=False)
t.head()

In [ ]:
# 1. How many movies has Judi Dench acted in?

len(cast[cast.name == 'Judi Dench'])

In [1]:
# Steal From Brandon Rhodes
# https://www.youtube.com/watch?v=5JnMutdy6Fw
# https://github.com/brandon-rhodes/pycon-pandas-tutorial/blob/master/All.ipynb

In [ ]:
# Why? Like algos for studing coding, most of the work is NOT the ML algo. It is a data sicnce thing.