## Notebook Is Awesome

## NumPy is FAST

### Basics
NumPy is the fundamental package for scientific computing with Python.
We get a powerful array object, sophisticated functions, random number capabilities and much more.

In [91]:
import numpy as np

### Arrays

In [92]:
a = np.array([2,3,4])

In [93]:
a

array([2, 3, 4])

In [94]:
a.dtype

dtype('int32')

In [95]:
a >= 3

array([False,  True,  True], dtype=bool)

In [96]:
a * 6

array([12, 18, 24])

### Multidimensional Arrays

In [97]:
m = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

In [98]:
m

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [99]:
m * 5

array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5]])

In [100]:
m[1]

array([0, 1, 0])

In [101]:
m[:, 0]

array([1, 0, 0])

### Utilits

In [102]:
np.linspace(0, 1, 9)  

array([ 0.   ,  0.125,  0.25 ,  0.375,  0.5  ,  0.625,  0.75 ,  0.875,  1.   ])

In [103]:
np.zeros([3,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

### Fast

In [104]:
a = np.arange(0, 2 ** 20)  

In [105]:
l = range(0, 2 ** 20)

In [106]:
len(a), len(l)

(1048576, 1048576)

In [107]:
a * a

array([       0,        1,        4, ..., -6291447, -4194300, -2097151])

In [108]:
%%timeit -n 3
[i*i for i in l]

3 loops, best of 3: 175 ms per loop


In [109]:
%%timeit -n 100
a * a

100 loops, best of 3: 1.55 ms per loop
